name: jubilant_json_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  path_provider: ^2.0.10
  dio_cookie_manager: ^2.1.3
  cupertino_icons: ^1.0.8
  cookie_jar: ^3.0.1
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^8.0.0

  camera: ^0.10.5+5
  image_cropper: ^5.0.1
  google_mlkit_text_recognition: ^0.10.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/logoCerfrance.png
    - assets/images/littleLogoCerfrance.png
    - .env
